version: '2'
catalog:
  name: "Backup"
  version: 1.0.0
  description: ""
  minimum_rancher_version: v1.0.0-rc2
services:
  nginx-proxy:
    start_on_create: true
  letsencrypt-nginx-proxy-companion:
    scale: 1
    start_on_create: true

