version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - VIRTUAL_HOST=jenkins.host1.swarm.flagbit.com
      - VIRTUAL_PORT=8443
    stdin_open: true
    network_mode: bridge
    volumes:
      - jenkins_jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /run/metadata:/run/metadata
      - /run/torcx:/run/torcx
    user: root
    tty: true
    ports:
      - 8443
    args:
      - httpPort=1
      - httpsPort=8443
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: master=true

volumes:
  jenkins_jenkins-data:
    external:
      name: "${volume}"